//
// Created by matej_000 on 16. 06. 2022.
//

#ifndef PAGESCANDEMO_CONVERSIONS_H
#define PAGESCANDEMO_CONVERSIONS_H


#define JAVA_BUFFER_TYPE_CUSTOM 0
#define JAVA_BUFFER_TYPE_INT_RGB 1
#define JAVA_BUFFER_TYPE_INT_ARGB 2
#define JAVA_BUFFER_TYPE_INT_ARGB_PRE 3
#define JAVA_BUFFER_TYPE_INT_BGR 4
#define JAVA_BUFFER_TYPE_3BYTE_BGR 5
#define JAVA_BUFFER_TYPE_4BYTE_ABGR 6
#define JAVA_BUFFER_TYPE_4BYTE_ABGR_PRE 7
#define JAVA_BUFFER_TYPE_USHORT_565_RGB 8
#define JAVA_BUFFER_TYPE_USHORT_555_RGB 9
#define JAVA_BUFFER_TYPE_BYTE_GRAY 10
#define JAVA_BUFFER_TYPE_USHORT_GRAY 11
#define JAVA_BUFFER_TYPE_BYTE_BINARY 12
#define JAVA_BUFFER_TYPE_JPEG 256
#define JAVA_BUFFER_TYPE_NV21 17
#define JAVA_BUFFER_TYPE_YUV_420_888 35
#define JAVA_BUFFER_TYPE_RGB656 1004
#define JAVA_BUFFER_TYPE_YUY2 1020

bool convert_image_to_mat(JNIEnv *jenv, cv::Mat& image, jobject jimage, int flags = cv::IMREAD_UNCHANGED);

bool convert_mat_to_bitmap(JNIEnv *jenv, jobject jbitmap, cv::Mat image);

#endif //PAGESCANDEMO_CONVERSIONS_H
